# 服务端口配置
server:
  port: 19903
  address: 0.0.0.0
#  ssl:
#    enabled: true
#    key-store: classpath:certs/server-keystore.p12
#    key-store-password: changeit
#    key-store-type: PKCS12
#    trust-store: classpath:certs/ca-truststore.p12
#    trust-store-password: changeit
#    trust-store-type: PKCS12
#    client-auth: want

spring:
  application:
    name: ms-auth

  cloud:
    # Nacos配置
    nacos:
      discovery:
        server-addr: 100.97.223.54:8848
        namespace: public
        group: DEFAULT_GROUP
        secure: false
  # 邮件服务配置
  mail:
    host: smtp.163.com # 邮件服务器地址
    port: 465 # SSL 端口
    username: camellia084@163.com # 发送邮件的邮箱
    password: DLiL2kNcruiAtVRH # 开通服务后得到的授权码
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.enable: true
      mail.default-encoding: utf-8 # 邮件内容的编码

  # Redis 配置
  data:
    redis:
      host: 100.97.223.54
      port: 6379
      password: camellia20.
      database: 2  # 使用 Redis 的数据库 2

      # Lettuce 客户端配置
      lettuce:
        pool:
          max-active: 100      # 最大活跃连接数
          max-idle: 50         # 最大空闲连接数
          min-idle: 10         # 最小空闲连接数
          max-wait: 5000       # 最大等待时间（毫秒）


# 阿里云短信服务配置
alibaba:
  signName: 白山茶
  templateCode: SMS_474831120
  accessKeyId: LTAI5tShgN5fSS7M9HkRSXjd
  accessKeySecret: 2S2p4DrTNaKbBqOYWdFezYDnTe0opq
  regionId: cn-hangzhou
  product: Dysmsapi
  domin: dysmsapi.aliyuncs.com

ai:
  qwen:
    api-key: sk-54b1779f9eb743faa8ac2a73091ce97d
    model: qwen3-max