server:
  port: 19901
  address: 0.0.0.0
#  ssl:
#    enabled: true
#    key-store: classpath:certs/server-keystore.p12
#    key-store-password: changeit
#    key-store-type: PKCS12
#    trust-store: classpath:certs/ca-truststore.p12
#    trust-store-password: changeit
#    trust-store-type: PKCS12
#    client-auth: need

ai:
  qwen:
    api-key: sk-54b1779f9eb743faa8ac2a73091ce97d
    model: qwen3-max

spring:
  application:
    name: ms-ai

  cloud:
    # Nacos配置
    nacos:
      discovery:
        ip: bg-mac-mini.tailfbfced.ts.net
        port: 19901
        server-addr: 100.97.223.54:8848
        namespace: public
        group: DEFAULT_GROUP
        secure: true


  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://100.97.223.54:3306/hotel?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
          username: root
          password: camellia20.
        house:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://100.97.223.54:3306/prhouseserver?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
          username: root
          password: camellia20.

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: mselasticsearch.domain


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

