server:
  port: 19902
  address: 0.0.0.0
spring:
  application:
    name: ms-user

  cloud:
    # Nacos配置
    nacos:
      discovery:
        server-addr: 100.97.223.54:8848
        namespace: public
        group: DEFAULT_GROUP
        secure: false


  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://100.97.223.54:3306/bit-mscloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
          username: root
          password: camellia20.

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: mselasticsearch.domain

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
