server:
  port: 19912
  ssl:
    enabled: true
    key-store: classpath:certs/server-keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    trust-store: classpath:certs/ca-truststore.p12
    trust-store-password: changeit
    trust-store-type: PKCS12
    client-auth: need   # 要求网关必须提供证书

spring:
  application:
    name: ms-elasticsearch

  cloud:
    # Nacos配置
    nacos:
      discovery:
        server-addr: 100.97.223.54:8848
        namespace: public
        group: DEFAULT_GROUP
        secure: true


  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://100.97.223.54:3306/hotel?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
          username: root
          password: camellia20.
        house:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://100.97.223.54:3306/prhouseserver?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
          username: root
          password: camellia20.

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: mselasticsearch.domain

elasticsearch:
  host: 100.97.223.54
  port: 9200
